Fetch CAPI version number from file name
Gets rid of next-version resource for generating github release

diff --git a/ci/git/generate_github_release b/ci/git/generate_github_release
--- a/ci/git/generate_github_release
+++ b/ci/git/generate_github_release
@@ -4,7 +4,6 @@ set -eu
 
 FINAL_RELEASE_DIR=capi-final-releases/
 PREVIOUS_RELEASE_TAG=$(cat github-published-release/tag)
-NEXT_VERSION_DIR=next-version/
 pushd capi-release
   SHA_CAPI=$(git rev-parse HEAD )
   echo $SHA_CAPI > ../$FINAL_RELEASE_DIR/commitish
@@ -20,7 +19,23 @@ pushd capi-release
   popd
 popd
 
-VERSION_CAPI=$(cat $NEXT_VERSION_DIR/version)
+ALL_CAPI_REL_TGZS=( "$FINAL_RELEASE_DIR"/capi-*.tgz )
+
+if [ ${#ALL_CAPI_REL_TGZS[@]} -gt 1 ]; then
+    echo "Error: More than one file matches the pattern 'capi-*.tgz'"
+    exit 1
+elif [[ ! -e ${ALL_CAPI_REL_TGZS[0]} ]]; then
+    echo "Error: No file matches the pattern 'capi-*.tgz'"
+    exit 1
+fi
+
+CAPI_REL_TGZ=$(basename "${ALL_CAPI_REL_TGZS[0]}")
+VERSION_CAPI=$(echo $CAPI_REL_TGZ | sed -e 's/^capi-//' -e 's/\.tgz$//')
+
+if [[ $VERSION_CAPI =~ ^[0-9]+\.[0-9]+\.[0-9]+- ]]; then  # Check if the version string is longer than expected
+    echo "Error: Invalid version string $VERSION_CAPI in file $CAPI_REL_TGZ"
+    exit 1
+fi
 
 echo "CAPI ${VERSION_CAPI}" > $FINAL_RELEASE_DIR/name
 echo "${VERSION_CAPI}" > $FINAL_RELEASE_DIR/version
